name: my_storage
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0-271.4.beta <3.0.0"

dependencies:
  appwrite: ^6.0.0
  bloc: ^8.0.3
  chewie: ^1.3.4
  cupertino_icons: ^1.0.2
  dropdown_button2: ^1.7.1
  file_picker: ^5.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  image_picker: ^0.8.5+3
  mime: ^1.0.2
  path_provider: ^2.0.11
  video_player: ^2.4.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
